name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  entry: ^0.0.9
  fast_immutable_collections: ^9.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  fpdart: ^1.1.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  guarded_go_router:
    git:
      url: https://github.com/harkairt/guarded_go_router
      ref: 19ea153d73d1ea8e99bf4d27d92f3fe7d82945f5
  hooks_riverpod: ^2.4.9
  json_serializable: ^6.7.1
  l10n:
    path: ../packages/l10n
  plugger: ^0.0.1
  responsive_builder: ^0.7.0
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  sentry_flutter: ^7.14.0
  shared_preferences: ^2.2.2
  stack_trace: ^1.11.1
  stored_notifier:
    git:
      url: https://github.com/harkairt/stored_notifier
      ref: 29d931fb1d6f63cd809ab72c22a88ab4520103d7
  theme_tailor: ^2.0.2
  theme_tailor_annotation: ^2.0.2
  v_flutter_core:
    git:
      url: https://github.com/Vlabs-development/v_flutter_core
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
